-- AlterTable
ALTER TABLE `AdGroupsRights` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `createdBy` VARCHAR(191) NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN `isDeleted` BOOLEAN NOT NULL DEFAULT false;
